import { describe, it, expect } from 'vitest';
import * as fc from 'fast-check';
import {
  serializeToneStack,
  deserializeToneStack,
  serializeFxChain,
  deserializeFxChain,
} from '@/lib/serialization';
import type { AmpParameters, AmpChannel } from '@/types/amp';
import type { FxPedalInstance } from '@/types/fx';
import type { ToneStackJSON } from '@/types/tone-stack';

// ── Shared Arbitraries ──

const channelArb = fc.constantFrom<AmpChannel>('clean', 'crunch', 'overdrive');

const togglesArb = fc.dictionary(
  fc.constantFrom('toneShift', 'deep', 'midBoost', 'midCut', 'bright', 'diode'),
  fc.boolean(),
);

const ampParamArb: fc.Arbitrary<AmpParameters> = fc.record({
  preampGain: fc.integer({ min: 1, max: 10 }),
  volume: fc.integer({ min: 1, max: 10 }),
  masterVolume: fc.integer({ min: 1, max: 10 }),
  masterGain: fc.integer({ min: 1, max: 10 }),
  bass: fc.integer({ min: 1, max: 10 }),
  middle: fc.integer({ min: 1, max: 10 }),
  treble: fc.integer({ min: 1, max: 10 }),
  tone: fc.integer({ min: 1, max: 10 }),
  presence: fc.integer({ min: 1, max: 10 }),
  resonance: fc.integer({ min: 1, max: 10 }),
  channel: channelArb,
  toggles: togglesArb,
});

const modelIdArb = fc.stringMatching(/^[a-z][a-z0-9-]{0,29}$/);

const pedalParamKeyArb = fc.constantFrom('drive', 'tone', 'level', 'mix', 'rate', 'depth');

const pedalParamsArb = fc.dictionary(
  pedalParamKeyArb,
  fc.integer({ min: 0, max: 100 }),
  { minKeys: 0, maxKeys: 4 },
);

const pedalDefIdArb = fc.constantFrom(
  'mac-super-comp', 'king-super-overdrive', 'tokyo-tube-screamer',
  'manhattan-big-muff', 'king-distortion', 'mac-phase-90',
);

const pedalInstanceArb = (index: number): fc.Arbitrary<FxPedalInstance> =>
  fc.record({
    definitionId: pedalDefIdArb,
    instanceId: fc.constant(`placeholder-${index}`),
    enabled: fc.boolean(),
    parameters: pedalParamsArb,
    position: fc.constant(index),
  });

const pedalArrayArb = fc
  .integer({ min: 0, max: 6 })
  .chain((len) =>
    len === 0
      ? fc.constant([] as FxPedalInstance[])
      : fc.tuple(...Array.from({ length: len }, (_, i) => pedalInstanceArb(i))).map(
          (arr) => arr as FxPedalInstance[],
        ),
  );

// ── Property 3: Tone stack serialization round-trip ──

/**
 * Property 3: Tone stack serialization round-trip
 * **Validates: Requirements 25.1, 25.2, 25.3**
 *
 * For any valid AmpParameters and modelId, serializeToneStack followed by
 * deserializeToneStack followed by serializeToneStack again SHALL produce
 * a JSON string identical to the first serialization.
 */
describe('Property 3: Tone stack serialization round-trip', () => {
  it('serialize → deserialize → serialize produces identical JSON', () => {
    fc.assert(
      fc.property(ampParamArb, modelIdArb, (params, modelId) => {
        const json1 = serializeToneStack(params, modelId);
        const { modelId: restoredModelId, params: restoredParams } =
          deserializeToneStack(json1);
        const json2 = serializeToneStack(restoredParams, restoredModelId);

        expect(JSON.stringify(json1)).toBe(JSON.stringify(json2));
      }),
      { numRuns: 100 },
    );
  });

  it('deserialize restores original params and modelId', () => {
    fc.assert(
      fc.property(ampParamArb, modelIdArb, (params, modelId) => {
        const json = serializeToneStack(params, modelId);
        const { modelId: restoredModelId, params: restoredParams } =
          deserializeToneStack(json);

        expect(restoredModelId).toBe(modelId);
        expect(restoredParams.preampGain).toBe(params.preampGain);
        expect(restoredParams.volume).toBe(params.volume);
        expect(restoredParams.masterVolume).toBe(params.masterVolume);
        expect(restoredParams.masterGain).toBe(params.masterGain);
        expect(restoredParams.bass).toBe(params.bass);
        expect(restoredParams.middle).toBe(params.middle);
        expect(restoredParams.treble).toBe(params.treble);
        expect(restoredParams.tone).toBe(params.tone);
        expect(restoredParams.presence).toBe(params.presence);
        expect(restoredParams.resonance).toBe(params.resonance);
        expect(restoredParams.channel).toBe(params.channel);
        expect(restoredParams.toggles).toEqual(params.toggles);
      }),
      { numRuns: 100 },
    );
  });
});


// ── Property 4: FX pedal chain serialization round-trip ──

/**
 * Property 4: FX pedal chain serialization round-trip
 * **Validates: Requirements 25.5, 25.6, 6.6**
 *
 * For any valid array of FxPedalInstance, serializeFxChain followed by
 * deserializeFxChain followed by serializeFxChain again SHALL produce
 * a JSON string identical to the first serialization. The round-trip
 * preserves definitionId, enabled, parameters, and position (instanceId
 * is regenerated by deserializeFxChain as `${definitionId}-${index}`).
 */
describe('Property 4: FX pedal chain serialization round-trip', () => {
  it('serialize → deserialize → serialize produces identical JSON', () => {
    fc.assert(
      fc.property(pedalArrayArb, (pedals) => {
        const json1 = serializeFxChain(pedals);
        const restored = deserializeFxChain(json1);
        const json2 = serializeFxChain(restored);

        expect(JSON.stringify(json1)).toBe(JSON.stringify(json2));
      }),
      { numRuns: 100 },
    );
  });

  it('deserialize preserves definitionId, enabled, parameters, and position', () => {
    fc.assert(
      fc.property(pedalArrayArb, (pedals) => {
        const json = serializeFxChain(pedals);
        const restored = deserializeFxChain(json);

        expect(restored).toHaveLength(pedals.length);
        for (let i = 0; i < pedals.length; i++) {
          expect(restored[i].definitionId).toBe(pedals[i].definitionId);
          expect(restored[i].enabled).toBe(pedals[i].enabled);
          expect(restored[i].parameters).toEqual(pedals[i].parameters);
          expect(restored[i].position).toBe(pedals[i].position);
        }
      }),
      { numRuns: 100 },
    );
  });
});

// ── Property 5: Invalid tone stack JSON error identification ──

/**
 * Property 5: Invalid tone stack JSON error identification
 * **Validates: Requirements 25.4**
 *
 * For any ToneStackJSON with a single field corrupted (wrong type,
 * out of range, or missing), deserializeToneStack SHALL throw an error
 * that identifies the corrupted field by name.
 */
describe('Property 5: Invalid tone stack JSON error identification', () => {
  /** Helper: build a valid ToneStackJSON from arbitrary params. */
  function makeValidJson(params: AmpParameters, modelId: string): ToneStackJSON {
    return serializeToneStack(params, modelId);
  }

  const numericParamKeys = [
    'preampGain',
    'volume',
    'masterVolume',
    'masterGain',
    'bass',
    'middle',
    'treble',
    'tone',
    'presence',
    'resonance',
  ] as const;

  const numericParamKeyArb = fc.constantFrom(...numericParamKeys);

  it('wrong type on a numeric parameter field throws error naming the field', () => {
    fc.assert(
      fc.property(ampParamArb, modelIdArb, numericParamKeyArb, (params, modelId, key) => {
        const json = makeValidJson(params, modelId);
        // Corrupt: set a numeric param to a string
        (json.parameters as Record<string, unknown>)[key] = 'not-a-number';

        expect(() => deserializeToneStack(json)).toThrow(`parameters.${key}`);
      }),
      { numRuns: 100 },
    );
  });

  it('out-of-range numeric parameter throws error naming the field', () => {
    const outOfRangeArb = fc.oneof(
      fc.integer({ min: 11, max: 1000 }),
      fc.integer({ min: -1000, max: 0 }),
    );

    fc.assert(
      fc.property(
        ampParamArb,
        modelIdArb,
        numericParamKeyArb,
        outOfRangeArb,
        (params, modelId, key, badValue) => {
          const json = makeValidJson(params, modelId);
          json.parameters[key] = badValue;

          expect(() => deserializeToneStack(json)).toThrow(`parameters.${key}`);
        },
      ),
      { numRuns: 100 },
    );
  });

  it('invalid channel value throws error naming "channel"', () => {
    const badChannelArb = fc
      .string({ minLength: 1, maxLength: 20 })
      .filter((s) => !['clean', 'crunch', 'overdrive'].includes(s));

    fc.assert(
      fc.property(ampParamArb, modelIdArb, badChannelArb, (params, modelId, badChannel) => {
        const json = makeValidJson(params, modelId);
        (json as Record<string, unknown>).channel = badChannel;

        expect(() => deserializeToneStack(json as ToneStackJSON)).toThrow('channel');
      }),
      { numRuns: 100 },
    );
  });

  it('non-boolean toggle value throws error naming the toggle key', () => {
    const toggleKeyArb = fc.constantFrom('toneShift', 'deep', 'midBoost', 'bright');

    fc.assert(
      fc.property(ampParamArb, modelIdArb, toggleKeyArb, (params, modelId, toggleKey) => {
        const json = makeValidJson(params, modelId);
        // Ensure the toggle key exists, then corrupt it
        json.toggles = { ...json.toggles, [toggleKey]: 'yes' as unknown as boolean };

        expect(() => deserializeToneStack(json as ToneStackJSON)).toThrow(
          `toggles.${toggleKey}`,
        );
      }),
      { numRuns: 100 },
    );
  });

  it('missing ampModelId throws error naming "ampModelId"', () => {
    fc.assert(
      fc.property(ampParamArb, modelIdArb, (params, modelId) => {
        const json = makeValidJson(params, modelId);
        (json as Record<string, unknown>).ampModelId = '';

        expect(() => deserializeToneStack(json as ToneStackJSON)).toThrow('ampModelId');
      }),
      { numRuns: 100 },
    );
  });

  it('wrong type on version throws error naming "version"', () => {
    fc.assert(
      fc.property(ampParamArb, modelIdArb, (params, modelId) => {
        const json = makeValidJson(params, modelId);
        (json as Record<string, unknown>).version = 'one';

        expect(() => deserializeToneStack(json as ToneStackJSON)).toThrow('version');
      }),
      { numRuns: 100 },
    );
  });
});
